export const dataEvents = [
  {
    color: "#0288d1",
    title: "Sara (grupo 1)",
    start: "9:30",
    duracion: 50,
    dia: "Lunes",
    place: "online",
  },
  {
    color: "#ff9633",
    title: "Carlos (grupo 1)",
    start: "10:30",
    duracion: 50,
    dia: "Lunes",
    place: "calle de sodio, 17",
  },
  {
    color: "#0fc4a7",
    title: "Amanda (grupo 2)",
    start: "11:40",
    duracion: 50,
    dia: "Lunes",
    place: "calle de sodio, 17",
  },
  {
    color: "#0fc4a7",
    title: "Pedro (propio)",
    start: "10:40",
    duracion: 180,
    dia: "Miercoles",
    place: "calle de sodio, 17",
  },
  {
    color: "#9575cd",
    title: "Documentos ",
    start: "12:20",
    duracion: 50,
    dia: "Viernes",
    place: "calle de sodio, 17",
  },
  {
    color: "#9575cd",
    title: "Documentos ",
    start: "20:10",
    duracion: 50,
    dia: "Viernes",
    place: "calle de sodio, 17",
  },
  {
    color: "#9575cd",
    title: "DIA LIBRE ",
    start: "7:00",
    duracion: 900,
    dia: "Domingo",
    place: "online",
  },
];
